apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: thoth-metrics-exporter-buildconfig
  annotations:
    description: >
      This is Thoth Metrics Exporter BuildConfig, this template is meant to be used by
      Bots, but could also be used by humans...
    openshift.io/display-name: 'Thoth Metrics Exporter BuildConfig'
    version: 0.5.0
    tags: thoth,thoth-metrics,thoth-metrics-exporter,ai-stacks,aistacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Thoth Metrics Exporter BuildConfig, this template is meant to be used
      by Bots, but could also be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.
    thoth-station.ninja/template-version: 0.5.0
  labels:
    template: thoth-metrics-exporter-buildconfig
    app: thoth
    component: metrics-exporter

parameters:
  - description: Name of the github repository to be used
    displayName: Git Repository
    required: true
    name: GITHUB_URL
    value: 'https://github.com/thoth-station/metrics-exporter'

  - description: Git reference to be used
    displayName: Git Reference
    required: true
    name: GITHUB_REF
    value: 'master'

  - description: >
      Tag of the output ImageStream the resulting container image should go to
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: 'latest'

  - description: Thamos Advise setup tag value
    displayName: THOTH_ADVISE
    required: true
    name: THOTH_ADVISE
    value: "0"

  - description: Thamos PROVENANCE_CHECK setup tag value
    displayName: PROVENANCE_CHECK
    required: true
    name: PROVENANCE_CHECK
    value: "0"

objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: metrics-exporter
      annotations:
        thoth-station.ninja/template-version: 0.5.0
      labels:
        app: thoth
        component: metrics-exporter
    spec:
      resources:
        requests:
          cpu: 1000m
          memory: 768Mi
        limits:
          cpu: 1000m
          memory: 768Mi
      output:
        to:
          kind: ImageStreamTag
          name: "metrics-exporter:${IMAGE_STREAM_TAG}"
      source:
        type: Git
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: s2i-thoth-ubi8-py36:latest
          env:
            - name: ENABLE_PIPENV
              value: '1'
            - name: UPGRADE_PIP_TO_LATEST
              value: '1'
            - name: WEB_CONCURRENCY
              value: '1'
            - name: "THOTH_DRY_RUN"
              value: "1"
            - name: "THOTH_ADVISE"
              value: ${THOTH_ADVISE}
            - name: "PROVENANCE_CHECK"
              value: ${PROVENANCE_CHECK}
            - name: "THAMOS_VERBOSE"
              value: "1"
            - name: "THAMOS_DEBUG"
              value: "0"
            - name: "THAMOS_CONFIG_TEMPLATE"
              value: ".thoth.yaml"
            - name: "THAMOS_CONFIG_EXPAND_ENV"
              value: "1"
      triggers:
        - type: ImageChange
          imageChange: {}
        - type: "Generic"
          generic:
            secretReference:
              name: generic-webhook-secret
